// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import AsyncStorage from '@react-native-async-storage/async-storage';
import { Linking } from 'react-native';
import type { Database } from './types';

const SUPABASE_URL = "https://mnyytgyfzuntoyhombjp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1ueXl0Z3lmenVudG95aG9tYmpwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc4NDQ4MjAsImV4cCI6MjA3MzQyMDgyMH0.lOsh1-7Jj_5xnHHN-lrmrwCfRIpE2i5jk4J4I8JNHt4";

// Custom storage adapter for React Native using AsyncStorage
const AsyncStorageAdapter = {
  getItem: async (key: string) => {
    return await AsyncStorage.getItem(key);
  },
  setItem: async (key: string, value: string) => {
    await AsyncStorage.setItem(key, value);
  },
  removeItem: async (key: string) => {
    await AsyncStorage.removeItem(key);
  },
};

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: AsyncStorageAdapter,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true, // Enable automatic URL detection for deep links
  }
});

// Helper function to extract session or OTP params from URL
export const extractAuthParamsFromUrl = (url: string): {
  access_token?: string;
  refresh_token?: string;
  token_hash?: string;
  type?: string;
} | null => {
  try {
    let paramsString = '';

    // Handle fragment (#) for implicit flow
    if (url.includes('#')) {
      paramsString = url.split('#')[1];
    } else if (url.includes('?')) {
      paramsString = url.split('?')[1];
    }

    if (paramsString) {
      const params = new URLSearchParams(paramsString);
      const access_token = params.get('access_token') || undefined;
      const refresh_token = params.get('refresh_token') || undefined;
      const token_hash = params.get('token_hash') || undefined;
      const type = params.get('type') || undefined;

      if (access_token && refresh_token) {
        return { access_token, refresh_token, type };
      }

      if (token_hash && type) {
        return { token_hash, type };
      }
    }
  } catch (e) {
    console.error('Error extracting auth params from URL:', e);
  }
  return null;
};

// Backward compatibility alias
export const extractSessionFromUrl = extractAuthParamsFromUrl;

// Store pending auth callback URL for AuthCallback screen to retrieve
// This is needed because the URL event may fire before AuthCallback mounts
let pendingAuthCallbackUrl: string | null = null;

export const getPendingAuthCallbackUrl = (): string | null => {
  const url = pendingAuthCallbackUrl;
  pendingAuthCallbackUrl = null; // Clear after retrieving
  return url;
};

export const setPendingAuthCallbackUrl = (url: string | null) => {
  pendingAuthCallbackUrl = url;
};

// Initialize deep link handling for auth
export const initializeAuthDeepLinking = (onSessionDetected: (type?: string) => void) => {
  // Handle initial URL (app opened via deep link)
  Linking.getInitialURL().then((url) => {
    if (url) {
      console.log('Supabase client - Initial URL:', url);
      handleAuthUrl(url, onSessionDetected);
    }
  });

  // Handle URLs when app is already open
  const subscription = Linking.addEventListener('url', (event) => {
    console.log('Supabase client - URL Event:', event.url);
    handleAuthUrl(event.url, onSessionDetected);
  });

  return () => {
    subscription.remove();
  };
};

const handleAuthUrl = async (url: string, onSessionDetected: (type?: string) => void) => {
  // For auth/callback URLs, store the URL for AuthCallback screen to process
  // OTP verification is handled exclusively by AuthCallback to avoid race conditions
  if (url.includes('auth/callback')) {
    console.log('Supabase client - Storing auth/callback URL for AuthCallback screen:', url);
    setPendingAuthCallbackUrl(url);
    return;
  }

  // Only handle non-callback auth-related deep links
  if (!url.includes('auth/')) {
    return;
  }

  const authParams = extractAuthParamsFromUrl(url);

  if (authParams?.access_token && authParams?.refresh_token) {
    // Handle implicit flow (access_token + refresh_token)
    console.log('Supabase client - Setting session from URL (implicit flow)');
    const { error } = await supabase.auth.setSession({
      access_token: authParams.access_token,
      refresh_token: authParams.refresh_token,
    });

    if (!error) {
      console.log('Supabase client - Session set successfully, type:', authParams.type);
      onSessionDetected(authParams.type);
    } else {
      console.error('Supabase client - Error setting session:', error);
    }
  }
};
