// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import AsyncStorage from '@react-native-async-storage/async-storage';
import { Linking } from 'react-native';
import type { Database } from './types';

const SUPABASE_URL = "https://mnyytgyfzuntoyhombjp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1ueXl0Z3lmenVudG95aG9tYmpwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc4NDQ4MjAsImV4cCI6MjA3MzQyMDgyMH0.lOsh1-7Jj_5xnHHN-lrmrwCfRIpE2i5jk4J4I8JNHt4";

// Custom storage adapter for React Native using AsyncStorage
const AsyncStorageAdapter = {
  getItem: async (key: string) => {
    return await AsyncStorage.getItem(key);
  },
  setItem: async (key: string, value: string) => {
    await AsyncStorage.setItem(key, value);
  },
  removeItem: async (key: string) => {
    await AsyncStorage.removeItem(key);
  },
};

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: AsyncStorageAdapter,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: false, // Disable automatic URL detection since we handle it manually
  }
});

// Helper function to extract session or OTP params from URL
export const extractAuthParamsFromUrl = (url: string): {
  access_token?: string;
  refresh_token?: string;
  token_hash?: string;
  type?: string;
} | null => {
  try {
    let paramsString = '';

    // Handle fragment (#) for implicit flow
    if (url.includes('#')) {
      paramsString = url.split('#')[1];
    } else if (url.includes('?')) {
      paramsString = url.split('?')[1];
    }

    if (paramsString) {
      const params = new URLSearchParams(paramsString);
      const access_token = params.get('access_token') || undefined;
      const refresh_token = params.get('refresh_token') || undefined;
      const token_hash = params.get('token_hash') || undefined;
      const type = params.get('type') || undefined;

      if (access_token && refresh_token) {
        return { access_token, refresh_token, type };
      }

      if (token_hash && type) {
        return { token_hash, type };
      }
    }
  } catch (e) {
    console.error('Error extracting auth params from URL:', e);
  }
  return null;
};

// Backward compatibility alias
export const extractSessionFromUrl = extractAuthParamsFromUrl;

// Initialize deep link handling for auth
export const initializeAuthDeepLinking = (onSessionDetected: (type?: string) => void) => {
  // Handle initial URL (app opened via deep link)
  Linking.getInitialURL().then((url) => {
    if (url) {
      console.log('Supabase client - Initial URL:', url);
      handleAuthUrl(url, onSessionDetected);
    }
  });

  // Handle URLs when app is already open
  const subscription = Linking.addEventListener('url', (event) => {
    console.log('Supabase client - URL Event:', event.url);
    handleAuthUrl(event.url, onSessionDetected);
  });

  return () => {
    subscription.remove();
  };
};

const handleAuthUrl = async (url: string, onSessionDetected: (type?: string) => void) => {
  // Skip auth callback URLs - let AuthCallback screen handle those via React Navigation
  // This prevents duplicate handling and race conditions
  if (url.includes('auth/callback')) {
    console.log('Supabase client - Skipping auth/callback URL, letting AuthCallback screen handle it');
    return;
  }

  // Only handle other auth-related deep links here
  if (!url.includes('auth/')) {
    return;
  }

  const authParams = extractAuthParamsFromUrl(url);

  if (authParams?.access_token && authParams?.refresh_token) {
    // Handle implicit flow (access_token + refresh_token)
    console.log('Supabase client - Setting session from URL (implicit flow)');
    const { error } = await supabase.auth.setSession({
      access_token: authParams.access_token,
      refresh_token: authParams.refresh_token,
    });

    if (!error) {
      console.log('Supabase client - Session set successfully, type:', authParams.type);
      onSessionDetected(authParams.type);
    } else {
      console.error('Supabase client - Error setting session:', error);
    }
  } else if (authParams?.token_hash && authParams?.type) {
    // Handle OTP flow (token_hash from Send Email Hook)
    console.log('Supabase client - Verifying OTP from URL, type:', authParams.type);

    // Map email_action_type to Supabase OTP type
    let otpType: 'signup' | 'recovery' | 'magiclink' | 'email_change' | 'email' = 'signup';
    if (authParams.type === 'recovery') {
      otpType = 'recovery';
    } else if (authParams.type === 'magiclink') {
      otpType = 'magiclink';
    } else if (authParams.type === 'email_change') {
      otpType = 'email_change';
    } else if (authParams.type === 'signup' || authParams.type === 'email') {
      otpType = 'signup';
    }

    const { data, error } = await supabase.auth.verifyOtp({
      token_hash: authParams.token_hash,
      type: otpType,
    });

    if (!error && data?.session) {
      console.log('Supabase client - OTP verified successfully, type:', authParams.type);
      onSessionDetected(authParams.type);
    } else {
      console.error('Supabase client - Error verifying OTP:', error);
    }
  }
};
